include/stringzilla/stringzilla.h, include/stringzilla/stringzilla.hpp, scripts/test.cpp
Writing some leak-checking found a few bugs and correctness issues.
`sz_string_init_from` would sometimes leave a residue of noise in the `space` field of the new string. Lightly refactor to share some of the logic so it is easier to see that all four fields are set for both shapes of string.
The copied code in move constructor and assignment shared some issues: the target for the move didn't actually get initialized with the values of the source. For the case of move assignment where the target already held values, we need to release the associated memory.
I'm happy with the test code for this; while this is probably not a complete inventory of memory leaks, we have an easy way to add tests for new ones we encounter.
=> Fix: leaks and semantics, testing for memory leaks

.gitignore, python/lib.c, scripts/test.py
32-bit and 64-bit offset logic assumed a `Strs` produced from by slicing a previous `Strs` started at offset 0. `str.split().slice([1:])`, for instance, produced impossible end offsets. This was the cause of some SEGVs and negative-length Python string constructions.
Deduplicate the 32-bit and 64-bit logic, and fix the bug in the single copy of the logic.
Test for 32-bit and 64-bit indices. Previous version of `lib.c` caused this test to SEGV or produce runtime errors about constructing Python strings of negative length depending on memory conditions.
=> Fix: python slices of splits used incorrect offsets.

CMakeLists.txt, include/stringzilla/stringzilla.h
Despite declaring it as extern "C", MSVC and Clang-Cl both still enforce that you cannot convert a void*0 (r-value) to a char* for some reason. As such had to added SZ_NULL_CHAR.
Clang-Cl also picks and chooses when it wants to use MSVC intrinsics over clang instrinsics, so added fixes for those issues.
Also cmakelist.txt just assumed PIC even tho it might not be available, so added a check.
NOTE: None of this code is tested as, both Clang-Cl and MSVC are not able to build any of the tests on my machine despite best efforts. #84
=> Added: Macro SZ_NULL_CHAR, Clang-CL instrinsics.

cli/README.md, cli/split.py, cli/wc.py
I used argparse to handle the arguments and flags, mirroring those of the system's split and wc commands to maintain a consistent user experience. The wc functionality is replicated to align with these system (GNU) commands. To avoid complicating usage, the implementation omits some flags from the split function (such as -a, -b, -C, -d), focusing instead on essential features: -t (separator), -n (chunk size), -l (line size), and standard input handling. Are there any suggestions for further improvements?
=> Standard-compliant ws and split implementation  (Issue 97 98)

pyproject.toml
At this point, the older images [crush the CI](https://github.com/ashvardanian/StringZilla/actions/runs/8120941587/job/22205963188), when running `yum update` inside the image:
```sh
+ /opt/python/cp38-cp38/bin/python -c 'import sys, json, os; json.dump(os.environ.copy(), sys.stdout)'
+ sh -c 'yum update -y && yum install -y glibc-devel wget python3-devel'
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrors.sinenomine.net/clefos?releasever=7&arch=s390x&repo=sclo&sub=rh error was
12: Timeout on http://mirrors.sinenomine.net/clefos?releasever=7&arch=s390x&repo=sclo&sub=rh: (28, 'Connection timed out after 30001 milliseconds')
One of the configured repositories failed (Unknown),
and yum doesn't have enough cached data to continue. At …
```
=> Make: Upgrade PyPy images for GCC12

.github/workflows/prerelease.yml, .gitignore, CMakeLists.txt, include/stringzilla/stringzilla.h, include/stringzilla/stringzilla.hpp, scripts/test.cpp
Just some fixes for building with MSVC
- Added MSVC C/C++ build to the windows workflow
- Fixed assertion with `range_(r)matches::iterator::operator==` when comparing iterators from different containers in debug mode
- Fixed incorrect `/arch` flags for MSVC when building `stringzilla_test_cpp20_x86_*`
=> Added MSVC build to workflow & Fixed MSVC build issues

scripts/bench.hpp, scripts/bench_search.cpp
Fixed Address Sanitizer errors when running `bench_search` in debug mode. These were caused due to the conversion from a character set (i.e. `sz::newlines()`) to `std::string` resulting in strings with an incorrect length.
<details>
<summary>Address Sanitizer output</summary>
```
StringZilla. Starting search benchmarks.
Parsed the dataset with:
- 1048576 words of mean length ~ 5.12 bytes
- 32768 lines of mean length ~ 128.54 bytes
Benchmarking for a newline symbol:
- std::string_view.find          0.3006 GB/s      27902428.1 ns          0 errors in        360 iterations              
- sz_find_serial                0.1551 GB/s      54083324.5 ns          0 errors in        188 iterations               
- sz_find_avx2                  0.4209 GB/s      19930871.6 ns          0 errors in …
```
=> Fixed Address Sanitizer issues with bench_search

CMakeLists.txt, c/lib.c, include/stringzilla/stringzilla.h, scripts/bench_sort.cpp
- Fixed unsupported `__attribute__` on MSVC
- Removed all MSVC warnings, so that `/WX` (treat warnings as errors) can now be enabled
=> Fixed MSVC build & warnings

scripts/bench_sort.cpp
Added MSVC `qsort_s` function to the sort benchmarks, as a replacement for `qsort_r` on linux,
=> Added the qsort_s bench function for MSVC

CMakeLists.txt
- Fixed CMake not setting custom C++ version for Clang.
- Fixed CMake putting the default C++ version (`set(CMAKE_CXX_STANDARD 17)`) after the custom one.
- Fixed CMake not setting `-march` for Clang/AppleClang (`-march=native` can be used, as long as we are not cross compiling). Which means that the Clang/MacOS workflows have `AVX2` enabled when running the test program.
- Added `ARM64` backend.
Fixes #124
=> Fixed CMake not settings some compiler flags correctly

.github/workflows/prerelease.yml, .github/workflows/release.yml
Updated the release.yml Clang version to 16, to avoid build issues.
This had got forgotten from #136 .
=> Update release.yml clang version

cli/wc.py
In the wc cli I fixed up a couple bugs,  added the files from arg, justified the output to match wc,  and sped up the longest line search. 
ref https://github.com/ashvardanian/StringZilla/issues/97
```
$ time python ../StringZilla/cli/wc.py -L  --files0-from delme
67 sz.js
51648 enwik9.txt
67 sz.js
102 tst.js
51884 total
real	0m1.184s
user	0m1.080s
sys	0m0.104s
$ time wc -L --files0-from delme
67 sz.js
51648 enwik9.txt
67 sz.js
102 tst.js
wc: ''$'\n': No such file or directory
51648 total
real	0m4.327s
user	0m4.184s
sys	0m0.142s
```
=> The wc cli has been fixed up

include/stringzilla/stringzilla.hpp
I met compilation error on gcc 14.2.1.
```
char uuid[36];
ashvardanian::stringzilla::randomize(ashvardanian::stringzilla::string_span(uuid, 35));
```
The error messages is following:
```
In file included from test07.cpp:15:
include/stringzilla/stringzilla.hpp: In instantiation of ‘void ashvardanian::stringzilla::randomize(basic_string_slice<char_type_>, string_view) [with char_type_ = char; string_view = basic_string_slice<const char>]’:
test07.cpp:39:39:   required from here
39 |   ashvardanian::stringzilla::randomize(ashvardanian::stringzilla::string_span(uuid, 35));
|   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/stringzilla/stringzilla.hpp:3770:14: error: no matching function for call to …
```
=> fix compilation error on `randomize`

python/lib.c
This commit deprecates `string.h` function usage in the Python binding implementation in favor of faster StringZilla operations.
=> Improve: Faster concatenation

c/lib.c, include/stringzilla/stringzilla.h, include/stringzilla/stringzilla.hpp, python/lib.c, scripts/bench_token.cpp, scripts/test.cpp, scripts/test.py
- 🆕  `sz_checksum(char const *, size_t)` C 99 interface
- 🆕  `sz::str().checksum()` C++ 11 interface
- 🆕  `sz.checksum(str)` Python interface
Database and other Systems Engineers, you can now use StringZilla to dynamically dispatch different check-sum kernels for AVX2 capable Haswell+ CPUs, AVX-512BW capable Ice Lake+ CPUs, and Arm NEON CPUs on mobile. In AVX-512, masked loads are used extensively, resulting in a 10% improvement even on typical English words, averaging 5 bytes in length and __20x performance improvement compared to the serial code for longer strings__.
On the technical side, on x86, the kernels use the well-known `SAD(text, zeros)` idiom to accumulate absolute differences between individual bytes into 64-bit words. It also uses bidirectional traversal to saturate the …
=> Checksums in AVX-512, AVX2, NEON

include/stringzilla/stringzilla.hpp
Should have returned `result`.
https://github.com/ashvardanian/StringZilla/blob/645539b468f3c2902061425684d9b002c43a14f7/include/stringzilla/stringzilla.hpp#L308-L312
=> Fix: Correct basic_charset operator

include/stringzilla/stringzilla.hpp, scripts/test.cpp
This PR fixes the issue where the last character of certain character arrays was not included in `basic_charset`. By explicitly adding a `'\0'` terminator to these arrays (e.g., `ascii_letters()`), all intended characters are now properly included.
In addition, new tests have been added for the ASCII utility functions provided by `sz::string` and `sz::string_view`. Previously, these tests would fail due to the missing final character. With this fix, they pass successfully, confirming that the issue is resolved. 
#200
=> Fix: Add null terminators to character arrays to include final characters

scripts/bench_sort.cpp
Fixes issues found in the hybrid bench sort function:
- intial string bytes inserted in the wrong order.
- `order` vector being erased (because `offset_in_word` was 0)
Which led to it having better performance that it actually had.
Also add logic to split the single final sorts into multiple may not be the most efficient or tidy. Which is needed as these functions would perform similar or worse than the equivalent `std`vm version, and now are around ~2x faster than there alternative.
Fixes: #208
=> Fix: hybrid bench sort issues

include/stringzilla/stringzilla.h
Fix: Corrected uninitialized bad shift table that could cause an infinite loop if some values were zero in the `_sz_[r]find_horspool_upto_256bytes_serial` methods.
When running the `benchmark_search` with `human_protein_1200row_800len.txt`, the executable would get stuck at `Benchmarking on present lines:` within the `_sz_find_horspool_upto_256bytes_serial` method.  This was because the `i` variable was not incrementing due to a zero value in the shift table.
Tested on Windows 11, Visual Studio 2022, `12th Gen Intel(R) Core(TM) i9-12900H `
=> Fixed uninitialized bad shift table

rust/lib.rs
=> Feature: HashMap traits for Rust

include/stringzilla/stringzilla.h
The bytes at the end of the (larger > 1M) inputs were not properly copied.
=> use proper offset for last bytes of avx512 copy

include/stringzilla/memory.h
The bytes at the end of the (larger > 1M) inputs were not properly copied.
=>  use proper offset for last bytes of skylake copy

CMakeLists.txt, README.md, binding.gyp, build.rs, c/stringzilla.c, include/stringzilla/compare.h, include/stringzilla/find.h, include/stringzilla/hash.h, include/stringzilla/stringzilla.h, include/stringzilla/types.h, scripts/bench.hpp, scripts/bench_container.cpp, scripts/bench_find.cpp, scripts/bench_memory.cpp, scripts/bench_token.cpp, scripts/test_stringzilla.cpp, scripts/test_stringzillas.cpp, scripts/test_stringzillas.cu, scripts/test_stringzillas.cuh, setup.py
Thanks to @Algunenano and the broader ClickHouse team for help, back-porting StringZilla kernels to older CPUs 🤗 
With this release:
- Substring search and hashing on CPUs from Westmere to Haswell will become at least 2x faster.
- Inferring Skylake capabilities in dynamic dispatch won't require `VAES` extensions only needed for Ice Lake and newer.
- MSVC will correctly detect Haswell, Ice Lake, and NEON capabilities for compile-time dispatch, lacking options to differentiate other platforms from macros.
=> Intel Westmere Kernels
